test/components/*: de-duplicate values
kinvolk/lokomotive pull request #1049
Opened 2020-10-07 07:34 UTC by knrt10

timeout and retryInterval were the same for most of the components and was
duplicated.

closes: #502
Signed-off-by: knrt10 <kautilya@kinvolk.io>

2020-10-07 07:39 UTC, invidian requested changes
Hm, it seems there is more occurrences, even with 5sec/5min values. 

I also think 9 minute tests could also get a const, like `TimeoutSlow` or something.

2020-10-07 07:42 UTC, knrt10 commented
There are 2 different values for timeout, 1 is 7min and other is 9 min. What should be the naming convention?

TimeoutSlow and TimeoutSlower?

2020-10-07 07:47 UTC, invidian commented
>There are 2 different values for timeout, 1 is 7min and other is 9 min. What should be the naming convention?

7 minutes can either be left as-is (as there is no duplication) or just increased to 9 minutes.

2020-10-07 08:42 UTC, invidian requested changes
Nice work @knrt10

2020-10-07 08:42 UTC, invidian commented on test/calico/metadata_access_test.go
>  	retryInterval = 1 * time.Second
It should be fine to retry after 5 seconds, we can get rid of this too.

2020-10-07 08:42 UTC, invidian commented on test/components/cert-manager/cert-manager_test.go
> +			testutil.WaitForDeployment(t, client, namespace, test.deployment, testutil.RetryInterval, testutil.Timeout) //nolint:goscope
It seems we should add `test := test` after for-range, rather than `//nolint:goscope`.

2020-10-07 08:42 UTC, invidian commented on test/components/util/util.go
> +	TimeoutSlower = time.Minute * 9
`Slower` sounds weird to me. I think just `Slow` might be better, so it indicates that this test case is slow, so it should get higher timeout. If we add `Slower`, we could also have `Slowest` etc. I think `Slow` is more clear.
```suggestion
	TimeoutSlow = time.Minute * 9
```

2020-10-07 08:55 UTC, invidian approved these changes
LGTM

2020-10-08 09:56 UTC, invidian commented
Rebase needed.

2020-10-08 09:57 UTC, invidian requested changes
Rebase needed.

2020-10-08 10:32 UTC, invidian approved these changes

2020-10-08 10:59 UTC, surajssd approved these changes
LGTM

2020-10-08 11:50 UTC, merged