Add tests for disabling BGP on Packet
kinvolk/lokomotive pull request #1178
Opened 2020-11-09 17:11 UTC by invidian

This commit adds e2e test, which verifies, that if worker pool has BGP
disabled on Packet, it actually remains disabled.

This test addresses
https://github.com/kinvolk/lokomotive/issues/548#issuecomment-694826634
to ensure, that we do not introduce a regression while adding CCM
support for Packet, as currentl CCM enables BGP on all workers in the
project, so it is expected that this test will fail with CCM enabled,
unless CCM is modified to only enable BGP on selected nodes.

Refs #548.

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

2020-11-09 18:49 UTC, invidian commented
Test that it works as expected: https://yard.lokomotive-k8s.net/teams/main/pipelines/pr-packet-fluo/jobs/test-lokomotive-packet-deployment-fluo/builds/122.2.

2020-11-10 06:59 UTC, ipochi requested changes
Thanks for the PR @invidian 

Couple of nits and typo in commit message `currentl`

2020-11-10 06:59 UTC, ipochi commented on test/platform/packet/packet_test.go
> +		t.Fatalf("creating Packet API client: %v", err)
```suggestion
		t.Fatalf("Creating Packet API client: %v", err)
```

2020-11-10 06:59 UTC, ipochi commented on test/platform/packet/packet_test.go
> +		t.Fatalf("listing devices in project %q: %v", projectID, err)
```suggestion
		t.Fatalf("Listing devices in project %q: %v", projectID, err)
```

2020-11-10 08:05 UTC, ipochi approved these changes
LGTM :tada:

2020-11-10 08:42 UTC, merged