parameterise envoy scraping interval
kinvolk/lokomotive pull request #1229
Opened 2020-12-02 08:28 UTC by surajssd

This commit adds a parameter to contour's component config, using which now users can choose what (prometheus) scrape interval they want for envoy.

# How to use

Deploy contour using following config:

```tf
component "contour" {
  enable_monitoring = true

  envoy {
    metrics_scrape_interval = "30s"
  }
}
```

And you can watch the field `interval` vary according to the value of `metrics_scrape_interval`. If the field `metrics_scrape_interval` is not provided then the `interval` field is also left out.

```bash
kubectl -n projectcontour get servicemonitor envoy -o yaml | grep interval
```

2020-12-02 08:54 UTC, invidian requested changes
I still have a feeling that:
- Increasing scrape interval might not be an optimal solution to solve the problem.
- Such customization seems very specific to me and having large amount of such will make it hard to maintain. I think we have to invest time in making generic customization mechanism. But even then, we will have to deprecate and eventually remove almost all of already added ones.

It would be good if someone experienced with Envoy and Prometheus could have a look at it.

2020-12-02 08:54 UTC, invidian commented on docs/configuration-reference/components/contour.md
> +| `envoy.metrics_scrape_interval` | Interval at which Prometheus will scrape Envoy. Valid only when `enable_monitoring` is set to `true`. |       -        | string
Table is not aligned + we should validate this document condition and have unit tests for it.

2020-12-02 09:06 UTC, surajssd commented
@invidian

> - Increasing scrape interval might not be an optimal solution to solve the problem.

This PR does not change anything unless user does. Any why reducing scrape interval might not solve the problem?

> - Such customization seems very specific to me and having large amount of such will make it hard to maintain. I think we have to invest time in making generic customization mechanism. But even then, we will have to deprecate and eventually remove almost all of already added ones.

What are you suggesting we do in this particular case? I agree we need a generic customization mechanism.

> It would be good if someone experienced with Envoy and Prometheus could have a look at it.

And who would that be?

2020-12-02 09:13 UTC, invidian commented
>This PR does not change anything unless user does. Any why reducing scrape interval might not solve the problem?

I'm not saying it won't solve the problem. I'm saying that it might not be the optimal solution. In https://github.com/kinvolk/lokomotive/issues/1194#issuecomment-730302433 I suggested testing with different bucket sizes for latency metrics. Or maybe some new metric should be added to Envoy to allow spotting those latency spikes more easily.

Increasing scrape interval seems more like a brute-force workaround to me, rather than a proper solution to the problem.

>What are you suggesting we do in this particular case?

Merge if it's urgent enough, switch focus to generic customization mechanism if not urgent IMO.

2020-12-04 10:47 UTC, iaguis approved these changes
lgtm

2020-12-04 11:00 UTC, merged