Update bootkube to include timeout fixes
kinvolk/lokomotive pull request #1236
Opened 2020-12-03 11:34 UTC by invidian

To include https://github.com/kinvolk/bootkube/pull/19

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

Draft to make sure it works as expected before I merge PR above and tag it. Doing some local tests too.

2020-12-07 12:48 UTC, iaguis requested changes

2020-12-07 12:48 UTC, iaguis commented on assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/ssh.tf
> +      # Terraform before we return error. We should be able to remove it once                                                 # https://github.com/hashicorp/terraform/issues/27121 is resolved.
is this missing a newline?

2020-12-07 12:48 UTC, iaguis commented on assets/terraform-modules/packet/flatcar-linux/kubernetes/ssh.tf
> +      # Use stdbuf to disable the buffer while printing logs to make sure everything is transmitted back to
is this missing a newline?

2020-12-07 12:48 UTC, iaguis commented on assets/terraform-modules/platforms/tinkerbell/controllers/ssh.tf
> +      # Use stdbuf to disable the buffer while printing logs to make sure everything is transmitted back to
is this missing a newline?

2020-12-07 16:01 UTC, invidian commented on assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/ssh.tf
> +      # Terraform before we return error. We should be able to remove it once                                                 # https://github.com/hashicorp/terraform/issues/27121 is resolved.
Yes, odd.

2020-12-17 10:24 UTC, knrt10 approved these changes

2020-12-17 10:56 UTC, iaguis approved these changes

2020-12-17 10:58 UTC, merged