kube-scheduler: create rolebinding
kinvolk/lokomotive pull request #1254
Opened 2020-12-07 13:47 UTC by knrt10

added a rolebinding for role `extension-apiserver-authentication-reader` for kube-scheduler

closes: #1096
Signed-off-by: knrt10 <kautilya@kinvolk.io>

2020-12-07 13:59 UTC, invidian requested changes
Please add an explanation why we add it in the commit message.

2020-12-07 13:59 UTC, invidian commented on assets/charts/control-plane/kubernetes/templates/kube-scheduler-role-binding.yaml
> +  name: system:configmaps-reader
Name should probably be unique. Like `kube-scheduler-extension-apiserver-authentication-reader` or something.

2020-12-07 14:21 UTC, invidian requested changes
How about the following for the commit message?
```
kube-scheduler: fix access to cluster certificates ConfigMap

Currently kube-scheduler is configured to dynamically load cluster certificates from
extension-apiserver-authentication-reader ConfigMap, but it is not authorized to do that
because its ServiceAccount is missing extension-apiserver-authentication-reader Role.

This causes kube-scheduler to not being able to read new cluster certificates dynamically
and makes it print annoying error message.

This commit adds missing RoleBinding for Role extension-apiserver-authentication-reader to
kube-scheduler ServiceAccount to fix this.

Closes: #1096

Signed-off-by: knrt10 <kautilya@kinvolk.io>
```

2020-12-07 14:30 UTC, invidian approved these changes

2020-12-08 07:05 UTC, surajssd approved these changes

2020-12-08 07:15 UTC, merged