aws_ebs_csi_driver: fix permission issue
kinvolk/lokomotive pull request #1271
Opened 2020-12-17 08:55 UTC by ipochi

Fixes: #1219

Whe trying to dynamically provision EBS volumes using the AWS EBS CSI
driver, we run into an error:
```
E1217 08:08:41.495598       1 driver.go:111] GRPC error: rpc error: code
= Internal desc = NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the
environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
```

There reason being that worker nodes are not given this permissions as
mentioned in the github repo of [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver#set-up-driver-permission).

This commit adds such permissions to the worker nodes.

Signed-off-by: Imran Pochi <imran@kinvolk.io>

2020-12-17 09:13 UTC, invidian requested changes
In order to get it to work, I think we need to pass `enable_csi` in AWS cluster template to worker pools.

2020-12-17 09:35 UTC, ipochi commented
@invidian 
Ah I forgot to commit one file.

I didnt add a per worker pool level `enable_csi` variable as I dont think it should be a per worker pool level setting but rather cluster wide.

2020-12-17 09:40 UTC, invidian commented
@ipochi did you forget to push as well? :)

2020-12-17 10:35 UTC, ipochi commented
@invidian updated.

2020-12-17 10:41 UTC, invidian requested changes

2020-12-17 10:41 UTC, invidian commented on pkg/platform/aws/template.go
> +  enable_csi   = {{$.Config.EnableCSI}}
Indentation.

2020-12-17 10:41 UTC, invidian commented on assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/workers.tf
> +# IAM Policy
```suggestion
# IAM Policy.
```

2020-12-17 10:41 UTC, invidian commented on assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/workers.tf
> +
Just one newline is enough?

2020-12-17 10:41 UTC, invidian commented on assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/variables.tf
> +  description = "Set up IAM role needed for dynamic volumes provisioning to work on AWS"
All other variables follow desription, type, default order.

2020-12-17 10:41 UTC, invidian commented on assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/variables.tf
> +  description = "Set up IAM role needed for dynamic volumes provisioning to work on AWS"
```suggestion
  type        = bool
  default     = false
  description = "Set up IAM role required for dynamic volumes provisioning."
```

2020-12-18 11:59 UTC, surajssd requested changes
We need an e2e test to verify if this is working fine, so we don't run into this later.

We can install a test application which requests storage using the ebs driver storage class and see if it came up fine!

2020-12-18 12:02 UTC, ipochi commented
> We need an e2e test to verify if this is working fine, so we don't run into this later.
> 
> We can install a test application which requests storage using the ebs driver storage class and see if it came up fine!

Without #1277 , AWS EBS CSI driver only works with static provisioning.
Correct me if I am wrong.

2020-12-18 12:09 UTC, invidian commented
>We need an e2e test to verify if this is working fine, so we don't run into this later.

> We can install a test application which requests storage using the ebs driver storage class and see if it came up fine!

This involves costs unfortunately, unless we have a reliable way to clean up those volumes automatically :|

2020-12-18 12:30 UTC, surajssd commented
> This involves costs unfortunately, unless we have a reliable way to clean up those volumes automatically :|

Can't we do it similar to external-dns, where we delete the PVCs and the volumes are also deleted by the ebs-driver?

2020-12-18 12:40 UTC, invidian commented
>Can't we do it similar to external-dns, where we delete the PVCs and the volumes are also deleted by the ebs-driver?

Probably, but still, dangling volumes cost money and DNS records not :smile:

2020-12-18 12:57 UTC, surajssd commented
> Probably, but still, dangling volumes cost money and DNS records not smile

We can have a clean up job to clean everything every night.

2020-12-18 13:13 UTC, ipochi commented
> > Probably, but still, dangling volumes cost money and DNS records not smile
> 
> We can have a clean up job to clean everything every night (separate from this PR).

I think in this case, the time spent on creating a cleanup job and making sure its working correctly, the only gain is that we can test if the volumes were dynamically provisioned, which IMO is not worth the effort for one test case.

This is one off once per updated component release or change in the component, I think for now a manual test suffices, rather than getting triggered on every CI run.

If there are multiple test cases then we can certainly think about having a cleanup job.

2020-12-18 15:06 UTC, invidian commented
I agree with @ipochi that for now manual testing should be sufficient for this.

2020-12-18 17:26 UTC, invidian requested changes
Last nit, otherwise LGTM

2020-12-18 17:26 UTC, invidian commented on assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/workers.tf
> +resource "aws_iam_instance_profile" "csi-driver" {
Resource names should use underscores.
```suggestion
resource "aws_iam_instance_profile" "csi_driver" {
```

2020-12-18 17:26 UTC, invidian commented on assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/workers.tf
> +resource "aws_iam_role_policy" "csi-driver" {
```suggestion
resource "aws_iam_role_policy" "csi_driver" {
```

2020-12-22 12:58 UTC, invidian approved these changes

2020-12-22 13:26 UTC, surajssd commented
@ipochi please create an issue for the left over work then we can move forward with merging this PR.

2020-12-22 13:36 UTC, ipochi commented
> @ipochi please create an issue for the left over work then we can move forward with merging this PR.

Created issue #1277

2020-12-22 13:40 UTC, surajssd commented
Typo: #1279 ?

2020-12-22 13:40 UTC, surajssd approved these changes

2020-12-22 13:41 UTC, merged