aws-ebs-csi-driver: add dynamic provisioning, resizing, snapshot options
kinvolk/lokomotive pull request #1277
Opened 2020-12-18 11:36 UTC by ipochi

Enhances the aws-ebs-csi-driver with additional configuration options such as:
 - Volume scheduling for dynamic provisioning
 - Volume resizing
 - Volme snapshotting

2020-12-18 11:45 UTC, knrt10 requested changes
Thanks for the PR, small NIT, rest LGTM

2020-12-18 11:45 UTC, knrt10 commented on pkg/components/aws-ebs-csi-driver/component.go
> +#Enable volume scheduling for dynamic volume provisioning
```suggestion
# Enable volume scheduling for dynamic volume provisioning.
```

2020-12-18 11:45 UTC, knrt10 commented on pkg/components/aws-ebs-csi-driver/component.go
> +# Enable volume resizing
```suggestion
# Enable volume resizing.
```

2020-12-18 11:45 UTC, knrt10 commented on pkg/components/aws-ebs-csi-driver/component.go
> +# Enable volume snapshot
```suggestion
# Enable volume snapshot.
```

2020-12-18 11:51 UTC, knrt10 submitted a review, later dismissed

2020-12-18 12:01 UTC, surajssd reviewed
Shouldn't these features be supported by default? Why does a user has to bother with these settings?

2020-12-18 12:13 UTC, ipochi commented
@surajssd 

> Shouldn't these features be supported by default? Why does a user has to bother with these settings?

They are not enabled by default.
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L38-#L45

> What are the implications of enabling snapshot by default?

Implications is that a  snapshot wont be created for a volume unless requested. But if it is requested then if the feature is not enabled you won't be able to create a Volume snapshot. The request can come from the user or Velero CSI plugin.

2020-12-18 12:44 UTC, ipochi commented
@surajssd @invidian 

Updated the PR with the required [CRDs](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/cluster/crd_snapshotter.yaml) for volumesnapshots.

2020-12-18 17:27 UTC, invidian commented
>They are not enabled by default.

If there is no disadvantages for enabling it by default, I think we should enable them.

2020-12-18 17:28 UTC, invidian approved these changes
LGTM

2020-12-22 13:29 UTC, surajssd commented
@ipochi since this is a CRD change please update the release notes section of the PR description. Then it is good to merge.

2020-12-22 13:35 UTC, ipochi commented
> @ipochi since this is a CRD change please update the release notes section of the PR description. Then it is good to merge.

@surajssd updated the PR description. Please check the description.

2020-12-22 13:55 UTC, knrt10 requested changes
Small commit message change

2020-12-22 13:55 UTC, knrt10 commented on docs/configuration-reference/components/aws-ebs-csi-driver.md
>  # aws-ebs-csi-driver.lokocfg
this commit message seems a bit weird. How about

`docs: update docs for aws-ebs-csi-driver`

2020-12-22 13:59 UTC, knrt10 approved these changes
+1

2020-12-22 14:00 UTC, invidian approved these changes

2020-12-22 14:02 UTC, surajssd approved these changes

2020-12-23 07:10 UTC, merged