RELEASE: Add steps to update the docs website entry
kinvolk/lokomotive pull request #1326
Opened 2021-01-15 13:59 UTC by surajssd

2021-01-15 13:59 UTC, surajssd commented
Waiting to get some insights from: https://github.com/kinvolk/docs/pull/10. Will update accordingly.

2021-01-28 07:14 UTC, knrt10 requested changes
What do you think?

2021-01-28 07:14 UTC, knrt10 commented on docs/RELEASING.md
> +Once the release is done. Create a pull request to the [docs repo](https://github.com/kinvolk/docs).
I would suggest

```suggestion
Once the release is done. Create a pull request to the [docs repo](https://github.com/kinvolk/docs) modifying the [_index.md](https://github.com/kinvolk/docs/blob/master/docs/lokomotive/_index.md) file.
```

2021-01-28 10:50 UTC, knrt10 approved these changes

2021-01-28 11:22 UTC, merged