Velero: restic plugin add tolerations
kinvolk/lokomotive pull request #1348
Opened 2021-01-27 06:10 UTC by knrt10

This commit adds a new attribute `tolerations` which will add tolerations to restic DaemonSet.

Since the cluster has multiple node pools with different purposes, it
adds an ability to deploy the restic DaemonSet on the nodes that need to
backup the PVC.

closes: #1334
Signed-off-by: knrt10 <kautilya@kinvolk.io>

2021-01-28 06:54 UTC, surajssd requested changes
Add a config conversion test.

2021-01-28 07:07 UTC, knrt10 commented
@surajssd added

2021-01-28 09:30 UTC, invidian commented
>@surajssd added

I don't see tests being added.

2021-01-28 09:34 UTC, knrt10 commented
Just to confirm, by config conversion doesn't it mean to add tolerations to restic config test and check whether it is right or not?

2021-01-28 09:37 UTC, invidian commented
>Just to confirm, by config conversion doesn't it mean to add tolerations to restic config tests and check whether it is right or not?

I think what @surajssd meant was to add tests, that toleration actually appears in the right place in the rendered manifests.

2021-01-29 06:47 UTC, knrt10 commented
@surajssd added the tests. Please check

2021-01-29 08:59 UTC, invidian requested changes

2021-01-29 08:59 UTC, invidian commented on pkg/components/velero/component_test.go
> +      toleration_seconds = "1"
Indentation.

2021-01-29 08:59 UTC, invidian commented on pkg/components/velero/component_test.go
> +	}
I suggest we use https://github.com/kinvolk/lokomotive/blob/efe364ea57e4d70e063ef6dbbeb304dc5a94f717/pkg/components/contour/component_test.go#L123-L126, which should be more accurate.

2021-01-29 08:59 UTC, invidian commented on pkg/components/velero/component_test.go
> +		t.Fatalf("Rendering manifests with valid config should succeed, got: %s", err)
Hm, we usually use `%v` for error formatting in tests.

2021-01-29 08:59 UTC, invidian commented on pkg/components/velero/component_test.go
> +	if d != nil {
`d` is type `hcl.Diagnostics`, we should use `HasErrors()` instead of `!=  nil`.

2021-01-29 09:38 UTC, invidian approved these changes
Just last nit, otherwise LGTM

2021-01-29 09:38 UTC, invidian commented on pkg/components/velero/component_test.go
> +	if d.HasErrors() {
We can put it in single line.

2021-01-29 09:42 UTC, invidian approved these changes

2021-01-29 10:47 UTC, surajssd approved these changes
LGTM Thanks.

2021-01-29 12:10 UTC, merged