prometheus-operator: Move the CRDs to control-plane
kinvolk/lokomotive pull request #1351
Opened 2021-01-27 14:14 UTC by surajssd

This commit moves the prometheus-operator CRDs to control-plane chart
Kubernetes.

This removes the cyclic dependency of components needing the
prometheus-operator CRDs installed before they can enable the
monitoring. This is especially the case with storage applications,
prometheus-operator needs storage and storage can only enable monitoring
after prometheus-operator is installed.

Fixes #557
Fixes #750

2021-01-27 14:18 UTC, invidian requested changes
What about https://github.com/kinvolk/lokomotive/pull/567#issuecomment-651558677? I still think those CRDs do not belong to control-plane in any way.

EDIT: And entire #567 actually, which also provides solution for those issues.

2021-01-27 14:29 UTC, surajssd commented
> The difference though is, that PodSecurityPolicy and NetworkPolicy are native resources, consumed by Kubernetes itself. ServiceMonitor is fully 3rd party resource. As a user, if I don't plan to install monitoring, I'd also expect to not find the CRDs installed.

We can add a knob to disable such installation, if user does not want the monitoring solution shipped by Lokomotive.

As of now we ship multiple monitoring resources that are not part of Prometheus Operator but they reside in control plane charts like the services (endpoints) that expose the monitoring ports of the control plane.

This PR enables us to monitor Calico, which we don't do currently.

2021-01-27 14:39 UTC, invidian commented
>We can add a knob to disable such installation, if user does not want the monitoring solution shipped by Lokomotive.

That knob would be on controlplane level, so where it doesn't belong. 

>As of now we ship multiple monitoring resources that are not part of Prometheus Operator but they reside in control plane charts like the services (endpoints) that expose the monitoring ports of the control plane.

In regular installations, kube-prometheus-stack delivers all controlplane services which are required for monitoring. Rather than going down with doing something the wrong way, I would rather fix remaining shortcomings.

I don't see much of a difference between this PR and #567. Both are workarounds for the deeper issues.

2021-02-12 07:42 UTC, knrt10 requested changes
Small NITs, apart from CI failing, LGTM.

2021-02-12 07:42 UTC, knrt10 commented on assets/charts/control-plane/prometheus-operator-crds/Chart.yaml
> +appVersion: "0.1.0"
It would be nice if we follow consistency. 

```suggestion
appVersion: 0.1.0
```

2021-02-12 07:42 UTC, knrt10 commented on assets/charts/control-plane/prometheus-operator-crds/Chart.yaml
> +description: A Helm chart for Prometheus Operator CRDS
We should follow per k8s documentation.

```suggestion
description: A Helm chart for Prometheus Operator CRDs.
```

2021-02-12 08:01 UTC, surajssd commented
I am not sure why `codespell` keeps failing, it does not fail locally.

2021-02-12 08:17 UTC, knrt10 commented
> I am not sure why codespell keeps failing, it does not fail locally.

@surajssd It because when running locally codespell uses the file `.codespell.skip`, but for CI you have add `./assets/charts/control-plane/prometheus-operator-crds/templates` also to `ci.yaml` file as currently their github action does not support file format.

2021-02-24 12:24 UTC, surajssd commented
> `install_prometheus_operator_crds` for the AKS platform too, as some components support monitoring

Prom Op CRDs is a control-plane only chart. Right now we don't have a way to install charts that are designated as control-plane and installed on managed platforms. There is not a way to add this component.

2022-06-01 11:43 UTC, closed without merging