docs: How to add worker pool to separate facility
kinvolk/lokomotive pull request #1361
Opened 2021-02-04 12:10 UTC by surajssd

This commit adds a doc that shows how to add a new worker pool to a
separate facility than the control plane and other worker pools.

2021-02-04 12:12 UTC, surajssd commented
Dependent on https://github.com/kinvolk/lokomotive/pull/1359 to be merged.

2021-03-01 13:56 UTC, iaguis requested changes
Nits

2021-03-01 13:56 UTC, iaguis commented on docs/how-to-guides/worker-pool-separate-facility.md
> +Go to the **Equinix Metal console** > **IPs & Networks** > **IPs**.
```suggestion
Go to **Equinix Metal console** > **IPs & Networks** > **IPs**.
```

2021-03-01 13:56 UTC, iaguis commented on docs/how-to-guides/worker-pool-separate-facility.md
> +Add the following snippet to your existing `lokocfg` file, under `cluster "packet"` section:
```suggestion
Add the following snippet to your existing `lokocfg` file, under the `cluster "packet"` section:
```

2021-03-01 15:06 UTC, iaguis approved these changes
lgtm

2021-03-02 09:45 UTC, merged