EM: Add restart on-failure for metadata service
kinvolk/lokomotive pull request #1362
Opened 2021-02-04 12:39 UTC by surajssd

This PR adds `Restart=on-failure` and `RestartSec=5s` to the metadata service.

Fixes https://github.com/kinvolk/lokomotive/issues/1298

---

The other services which have `Type=oneshot` are following: `wait-for-dns`, `bootkube`, `delete-node`, `create-etcd-config`, `persist-data-raid`.

Most of them are the type of services which we want them to fail early and the user know about it, instead of them endlessly trying and someone else doing a time out on them.

2021-02-04 12:51 UTC, knrt10 commented
Seeing this PR, I think we should slowly start changing Packet -> Equinx Metal

2021-02-05 13:19 UTC, invidian commented
>Seeing this PR, I think we should slowly start changing Packet -> Equinx Metal

We have #1060 :)

2021-02-05 13:34 UTC, invidian requested changes
>The other services which have Type=oneshot are following: wait-for-dns, bootkube, delete-node, create-etcd-config, persist-data-raid.

> Most of them are the type of services which we want them to fail early and the user know about it, instead of them endlessly trying and someone else doing a time out on them.

If there is a DNS outage, I think we should retry `wait-for-dns.service`, as it will block starting kubelet.

`delete-node.service` we should also retry IMO, so the node does not go away unregistered. As the pods will stay assigned for long on this node and won't be re-scheduled.

2 points above also applies to other platforms, not only Packet.

2021-02-05 13:34 UTC, invidian commented on assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
> +        RestartSec=5s
I suggest we use `10s` as upstream does: https://github.com/kinvolk/coreos-overlay/pull/768/commits/069f3ded1103136a6f121d5e93c9c051a3e5dc25.

2021-02-08 10:11 UTC, surajssd commented
> If there is a DNS outage, I think we should retry wait-for-dns.service, as it will block starting kubelet.
> delete-node.service we should also retry IMO, so the node does not go away unregistered. As the pods will stay assigned for long on this node and won't be re-scheduled.

I don't know what the unforeseen consequences will be for adding retries for `wait-for-dns` and `delete-node`, but lets try. I can only see them doing indefinite attempt to reconcile leaving user stranded either at installation or while removing the node.

2021-02-09 09:46 UTC, invidian approved these changes

2021-02-11 20:59 UTC, pothos commented
One more thing to consider: The `oneshot` services will be triggered again when the service that depends on it is restarted. I would add `RemainAfterExit=yes` everywhere, too (but for the resolv.conf waiter it seems harmless if it's triggered on a kubelet restart).

2021-02-12 13:03 UTC, invidian commented
Good point @pothos.

> I can wait until #1368 is merged.

This is now merged.

2021-02-12 14:32 UTC, merged

2021-02-12 14:33 UTC, invidian commented
@surajssd did you see @pothos comment before merging? Did you verify what he suggests?

2021-02-12 14:35 UTC, surajssd commented
> @surajssd did you see @pothos comment before merging? Did you verify what he suggests?

Yep, I thought it is to be done in a separate PR. `This is now merged.` kinda hinted me towards it is good to merge this one.

2021-02-12 14:36 UTC, surajssd commented
Creating a new issue for that Kai has suggested.