Add cluster-autoscaler update check
kinvolk/lokomotive pull request #862
Opened 2020-08-26 12:34 UTC by knrt10

To be merged after #859 

Signed-off-by: knrt10 <kautilya@kinvolk.io>

2020-08-26 13:09 UTC, invidian reviewed
This should close #809

2020-08-27 09:41 UTC, invidian commented
>This should close #809

@knrt10 mind adding `Closes #809` to commit message and PR description?

2020-08-27 09:44 UTC, knrt10 commented
Updated

2020-08-27 10:40 UTC, invidian requested changes

2020-08-27 10:40 UTC, invidian commented on scripts/find-updates.sh
> +printf "${format}" "cluster-autoscaler" "cluster-autoscaler-chart-${current_version}" "${version}"
Hm, I'd strip `cluster-autoscaler-chart-` somehow :/

2020-08-27 10:43 UTC, knrt10 commented on scripts/find-updates.sh
> +printf "${format}" "cluster-autoscaler" "cluster-autoscaler-chart-${current_version}" "${version}"
Cool

2020-08-27 11:00 UTC, invidian approved these changes
LGTM

2020-08-27 11:02 UTC, knrt10 commented
Merging it, as this is small change and won't affect lokomotive

2020-08-27 11:02 UTC, merged