components/metallb: Add missing autodiscovery labels
kinvolk/lokomotive pull request #990
Opened 2020-09-18 16:22 UTC by johananl

In order to allow users to control all supported BGP parameters by
specifying labels in worker pool config, we need to specify mappings
for them.

Fixes #987.

To test this change, deploy a cluster using a config similar to the following:

```hcl
cluster "packet" {
  asset_dir        = "./assets"
  cluster_name     = "my-cluster"
  controller_count = 1
  controller_type  = "t1.small.x86"
  dns {
    provider = "route53"
    zone     = "example.com"
  }
  facility    = "ams1"
  project_id = "fake"
  ssh_pubkeys       = ["ssh-rsa ..."]
  management_cidrs  = ["0.0.0.0/0"]
  node_private_cidr = "10.1.1.0/25"

  worker_pool "pool-1" {
    count     = 2
    node_type = "t1.small.x86"
    # Example: configure hold time and peer port by setting autodiscovery labels
    labels    = "metallb.lokomotive.io/hold-time=3s,metallb.lokomotive.io/peer-port=1179"
  }
}

component "metallb" {
  address_pools = {
    default = ["147.1.2.3/32"]
  }
}

```

2020-09-18 16:24 UTC, invidian approved these changes
LGTM

2020-09-18 17:10 UTC, iaguis approved these changes
lgtm

2020-09-22 06:49 UTC, surajssd requested changes
Please add an e2e test to verify these labels are taking effect?

2020-09-22 11:23 UTC, johananl commented
> Please add an e2e test to verify these labels are taking effect?

Since we're already verifying the component renders these labels in a unit test, what would be checking by adding an e2e test for this? AFAICT such a test would verify that the *API server* actually writes the ConfigMap we provide. Do you see value in that?

2020-09-22 15:04 UTC, surajssd approved these changes
Ah I didn't realise that the unit test was updated as well. Cool LGTM. Sorry for the noise.

2020-09-22 18:10 UTC, merged